---
title: "Final Project"
author: "Xunyuan Sun & Jing Du"
date: "4.19.2020"
output: html_notebook
---

## Clean up environment and load packages
```{r}
# clean up the RStudio environment 
rm(list = ls())

# load all packages here: `mosaic`, `tidyverse`, `DataComputing`, `tidyr` and all others used
library(mosaic)
library(DataComputing)
library(tidyverse)
library(tidyr)
```


## Data Intake

```{r}
# Import and Inspect data
Census_Tract_2015 <-
  read.csv("https://raw.githubusercontent.com/XYSunPSU/Final-Project/master/acs2015_census_tract_data.csv", header = T)

Census_Tract_2015 %>%
  head(5)
```

```{r}
Census_Tract_2017 <-
  read.csv("https://raw.githubusercontent.com/XYSunPSU/Final-Project/master/acs2017_census_tract_data.csv", header = T)

Census_Tract_2017 %>%
  head(5)
```

## Formalize Data Frame

```{r}
# remove state and county from Census_Tract_2017
CenTract2017 <-
  Census_Tract_2017 %>%
  select(-State, -County)
```

```{r}
# add suffix to each column in each data frame
colnames(Census_Tract_2015) <- paste(colnames(Census_Tract_2015), "2015", sep = "_")

CenTract2017 <-
  CenTract2017 %>%
  rename_all(paste0, "_2017")
```

```{r}
# rename columns
CenTract2015 <-
  Census_Tract_2015 %>%
  rename(TractID_2015 = "CensusTract_2015", State = "State_2015", County = "County_2015")
```


## Find unemployement rate change in each county in Pennsylvania

1. Filter data where state is pennsylvania
```{r}
PennStateCensusTract <-
  CenTract2015 %>%
  inner_join(CenTract2017, by = c("TractID_2015" = "TractId_2017")) %>%
  filter(State == "Pennsylvania")
```

2. Calculate the exactly number of people who is unemployed
```{r}
UnemploymentRateChange <-
  PennStateCensusTract %>%
  select(County, TotalPop_2015, Unemployment_2015, TotalPop_2017, Unemployment_2017) %>%
  mutate(Unemployed2015 = TotalPop_2015 * Unemployment_2015 * 0.01, 
         Unemployed2017 = TotalPop_2017 * Unemployment_2017 * 0.01) %>%
  mutate_at(vars(Unemployed2015, Unemployed2017), list(~ round(., 0)))
```


